from pymongo import MongoClient
from datetime import datetime

# Connect to MongoDB
client = MongoClient(
    "mongodb+srv://ashishpandya7122000:SBKphuP0FM03fiov@chatbot.uta4z.mongodb.net/todo_db?retryWrites=true&w=majority&tls=true&connectTimeoutMS=30000&socketTimeoutMS=30000"
)

db = client.todo_db
orders_collection = db["orders_collection"]

# 20 demo records to insert
demo_records = [
    {
        "order_number": "200001",
        "first_name": "John",
        "last_name": "Doe",
        "mobile_number": "9876543210",
        "items": ["Water Camper"],
        "capacity": "Large",
        "order_status": "Shipped",
        "order_date": "2025-03-01",
    },
    {
        "order_number": "200002",
        "first_name": "Jane",
        "last_name": "Smith",
        "mobile_number": "8765432109",
        "items": ["Water Bottle"],
        "capacity": "Medium",
        "order_status": "Processing",
        "order_date": "2025-03-02",
    },
    {
        "order_number": "200003",
        "first_name": "Alice",
        "last_name": "Brown",
        "mobile_number": "7654321098",
        "items": ["Water Camper", "Water Bottle"],
        "capacity": "Small",
        "order_status": "Delivered",
        "order_date": "2025-03-03",
    },
    {
        "order_number": "200004",
        "first_name": "Bob",
        "last_name": "Johnson",
        "mobile_number": "6543210987",
        "items": ["Water Camper"],
        "capacity": "Medium",
        "order_status": "Shipped",
        "order_date": "2025-03-04",
    },
    {
        "order_number": "200005",
        "first_name": "Charlie",
        "last_name": "Williams",
        "mobile_number": "5432109876",
        "items": ["Water Bottle"],
        "capacity": "Large",
        "order_status": "Processing",
        "order_date": "2025-03-05",
    },
    {
        "order_number": "200006",
        "first_name": "David",
        "last_name": "Jones",
        "mobile_number": "4321098765",
        "items": ["Water Camper", "Water Bottle"],
        "capacity": "Large",
        "order_status": "Delivered",
        "order_date": "2025-03-06",
    },
    {
        "order_number": "200007",
        "first_name": "Emily",
        "last_name": "Garcia",
        "mobile_number": "3210987654",
        "items": ["Water Camper"],
        "capacity": "Small",
        "order_status": "Shipped",
        "order_date": "2025-03-07",
    },
    {
        "order_number": "200008",
        "first_name": "Frank",
        "last_name": "Martinez",
        "mobile_number": "2109876543",
        "items": ["Water Bottle"],
        "capacity": "Medium",
        "order_status": "Processing",
        "order_date": "2025-03-08",
    },
    {
        "order_number": "200009",
        "first_name": "Grace",
        "last_name": "Hernandez",
        "mobile_number": "1098765432",
        "items": ["Water Camper", "Water Bottle"],
        "capacity": "Small",
        "order_status": "Delivered",
        "order_date": "2025-03-09",
    },
    {
        "order_number": "200010",
        "first_name": "Hannah",
        "last_name": "Lopez",
        "mobile_number": "9988776655",
        "items": ["Water Camper"],
        "capacity": "Large",
        "order_status": "Shipped",
        "order_date": "2025-03-10",
    },
    {
        "order_number": "200011",
        "first_name": "Ian",
        "last_name": "Gonzalez",
        "mobile_number": "8877665544",
        "items": ["Water Bottle"],
        "capacity": "Medium",
        "order_status": "Processing",
        "order_date": "2025-03-11",
    },
    {
        "order_number": "200012",
        "first_name": "Jack",
        "last_name": "Wilson",
        "mobile_number": "7766554433",
        "items": ["Water Camper", "Water Bottle"],
        "capacity": "Large",
        "order_status": "Delivered",
        "order_date": "2025-03-12",
    },
    {
        "order_number": "200013",
        "first_name": "Karen",
        "last_name": "Anderson",
        "mobile_number": "6655443322",
        "items": ["Water Camper"],
        "capacity": "Small",
        "order_status": "Shipped",
        "order_date": "2025-03-13",
    },
    {
        "order_number": "200014",
        "first_name": "Liam",
        "last_name": "Thomas",
        "mobile_number": "5544332211",
        "items": ["Water Bottle"],
        "capacity": "Medium",
        "order_status": "Processing",
        "order_date": "2025-03-14",
    },
    {
        "order_number": "200015",
        "first_name": "Mia",
        "last_name": "Taylor",
        "mobile_number": "4433221100",
        "items": ["Water Camper", "Water Bottle"],
        "capacity": "Large",
        "order_status": "Delivered",
        "order_date": "2025-03-15",
    },
    {
        "order_number": "200016",
        "first_name": "Nathan",
        "last_name": "Moore",
        "mobile_number": "3322110099",
        "items": ["Water Camper"],
        "capacity": "Small",
        "order_status": "Shipped",
        "order_date": "2025-03-16",
    },
    {
        "order_number": "200017",
        "first_name": "Olivia",
        "last_name": "Jackson",
        "mobile_number": "2211009988",
        "items": ["Water Bottle"],
        "capacity": "Medium",
        "order_status": "Processing",
        "order_date": "2025-03-17",
    },
    {
        "order_number": "200018",
        "first_name": "Paul",
        "last_name": "White",
        "mobile_number": "1100998877",
        "items": ["Water Camper", "Water Bottle"],
        "capacity": "Large",
        "order_status": "Delivered",
        "order_date": "2025-03-18",
    },
    {
        "order_number": "200019",
        "first_name": "Quinn",
        "last_name": "Harris",
        "mobile_number": "0099887766",
        "items": ["Water Camper"],
        "capacity": "Medium",
        "order_status": "Shipped",
        "order_date": "2025-03-19",
    },
    {
        "order_number": "200020",
        "first_name": "Rachel",
        "last_name": "Clark",
        "mobile_number": "9988776655",
        "items": ["Water Bottle"],
        "capacity": "Small",
        "order_status": "Processing",
        "order_date": "2025-03-20",
    },
]

# Insert demo records
try:
    result = orders_collection.insert_many(demo_records)
    print(f"Inserted {len(result.inserted_ids)} demo records successfully!")
except Exception as e:
    print(f"Error inserting demo records: {e}")
